version: '3'
services:
  ncds:
    image: node:8-alpine
    working_dir: /app
    container_name: ncds
    command: sh -c "yarn && yarn start"
    volumes:
      - .:/app
    network_mode: "host"
    user: 1000:1000

  mongo:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 127.0.0.1:3002:8081
    network_mode: host
    environment:
     - ME_CONFIG_MONGODB_SERVER=localhost
     - ME_CONFIG_MONGODB_PORT=27017